---
- name: Install monitoring tools
  hosts: all
  tasks:
    - name: Install elasticsearch
      include_role:
        name: elk
    
    - name: Install nagios for Ubuntu
      include_role:
        name: nagios_Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install nagios for Centos
      include_role:
        name: nagios_CentOS
      when: ansible_facts['distribution'] == 'CentOS'
    
    - name: Install grafana
      include_role:
        name: grafana
          
    - name: Install prometheus for Ubuntu
      include_role:
        name: prometheus_Ubuntu
      when: ansible_facts['distribution'] == 'Ubuntu'

    - name: Install prometheus for Centos
      include_role:
        name: prometheus_CentOS
      when: ansible_facts['distribution'] == 'CentOS'
